### ISSUE TITLE
Artificial data figures

### ISSUE THREAD

**Issue by martinferianc** [lennelov/endd-reproduce#73]
Thank you very much for your great work. I was wondering whether you have been successful at reproducing the artificial data experiment?

**Comment by toomasliiv** [comment]
Hi!

Thank you for your interest in our work. In our reproducibility paper, which you can find at https://rescience.github.io/bibliography/Liiv_2021.html, we detail our findings on the artificial dataset in Appendix B. The corresponding source code is available in this directory, specifically in https://github.com/lennelov/endd-reproduce/blob/master/code/scripts/explore_spiral_data.py. 

Feel free to write again if you have any further questions.

**Comment by martinferianc** [comment]
Thank you for your help and an extremely fast reply!
